# numpy 기본 실습

In [2]:
import numpy

In [4]:
import numpy as np

In [6]:
np

<module 'numpy' from 'C:\\playdata_lab\\data_analysis\\da_venv\\lib\\site-packages\\numpy\\__init__.py'>

## ndarray 생성 및 데이터 타입 확인

In [9]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [11]:
a

[1, 2, 3, 4, 5]

In [14]:
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [20]:
type(arr)

numpy.ndarray

In [23]:
arr.dtype
# 2진수 32비트로 표현한다는 뜻
# 객체 안에 값을 넣어 각각 요소의 타입이 뭔지 확인

dtype('int32')

In [18]:
arr2 = np.array(a, dtype=float)
arr2

array([1., 2., 3., 4., 5.])

In [25]:
arr2.dtype
# numpy array의 요소의 데이터 type 확인
# float는 2진수 64비트로 표현

dtype('float64')

In [27]:
# 2차원 리스트
mylist2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
mylist2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [31]:
arr3 = np.array(mylist2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## ndarray의 shape(형태) 확인

In [59]:
arr3.shape
# 2행 4열

(2, 4)

## numpy array의 data 타입 확인

In [36]:
mylist = [1, 3.14, 'joy', '1234']
mylist

[1, 3.14, 'joy', '1234']

In [38]:
mylist[1]

3.14

In [40]:
arr = np.array(mylist)
arr

array(['1', '3.14', 'joy', '1234'], dtype='<U32')

In [42]:
arr.dtype

dtype('<U32')

In [45]:
mylist1 = [1, 1.2, 2, 2.3]
arr1 = np.array(mylist1)
arr1

array([1. , 1.2, 2. , 2.3])

In [47]:
arr1.dtype

dtype('float64')

In [49]:
arr2 = np.array(mylist1, dtype="float32")

In [51]:
arr2.dtype

dtype('float32')

In [55]:
arr = np.array([1, 3.14, '1234'], dtype=int)
arr

array([   1,    3, 1234])

In [60]:
# dtype 지정시 mylist list에 문자 자료형이 아닌 진짜 문자가 포함되어 있으면 오류 발생
arr = np.array([1, 3.14, '1234', 'smile'], dtype=int)

ValueError: invalid literal for int() with base 10: 'smile'

#### 4. 슬라이싱
배열의 부분을 추출하는 기능

In [62]:
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [64]:
arr.shape

(10,)

indexing

In [67]:
# 1차원 array

In [69]:
arr[0]

10

In [71]:
arr[4]

14

In [73]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [75]:
arr[0], arr[5]

(10, 15)

In [77]:
arr[-1], arr[6]

(19, 16)

In [79]:
arr[-10], arr[-6]

(10, 14)

In [81]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

In [82]:
# 2차원 array

In [98]:
arr2d = np.array([ [1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]
                ])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
arr2d.shape

(3, 4)

In [95]:
# 2차원 ndarray 요소 확인
# arr2d[행 인덱스, 열 인덱스]

In [101]:
# 3행 전체
arr2d[2]

array([ 9, 10, 11, 12])

In [103]:
arr2d[0,2]

3

In [105]:
arr2d[2,3], arr2d[0,2]

(12, 3)

In [107]:
# 특정 위치의 값 변경
arr2d[2,3] = 13
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13]])

In [110]:
# 3차원 array
arr3d = np.array([ [[1,2],[3,4]],
                   [[5,6],[7,8]],
                   [[9,10],[11,12]]
                ])
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [111]:
arr3d.shape

(3, 2, 2)

### 범위 색인
1차원
- arr[start:stop:step]
- arr[::-1] # step이 음수인 경우 거꾸로 출력

In [114]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [116]:
# 정렬이 아닌 순서를 거꾸로 하는 것
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [118]:
# index 1 이상 끝까지
arr[1:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [120]:
# 처음~ (5-1)까지 (5에서 stop)
arr[:5]

array([10, 11, 12, 13, 14])

In [122]:
# index 1~ (5-1)까지 (5에서 stop)
arr[1:6]

array([11, 12, 13, 14, 15])

In [124]:
# 처음~ (마지막-1)까지 (마지막에서 stop)
arr[:-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [127]:
# arr[start:stop:step]
arr[0:5:2]
arr[0:5:1]

array([10, 11, 12, 13, 14])

In [135]:
arr[:6:2], arr[:2:1]
# arr[:-1:2], arr[:2:1]

(array([10, 12, 14]), array([10, 11]))

#### 2차원
arr2d[행start:행stop, 열start:열stop]

In [138]:
arr2d = np.array([ [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12] 
                ])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
# 0 row(행)의 값을 모두 슬라이싱하기
arr2d[0, :]

array([1, 2, 3, 4])

In [142]:
# 3 column(열)을 모두 슬라이싱
arr2d[:, 2]

array([ 3,  7, 11])

In [145]:
# 부분적으로 슬라이싱
# 3행 전까지의 모든 열
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
# 부분적으로 슬라이싱
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

In [150]:
# 문제 : 다음과 같이 슬라이싱
# - 행 : 1~3행까지
# - 열 : 1부터 모두
# ?? arr2d[:2, :]
arr2d[1:3, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [154]:
# 문제 : 
arr2d[:2, 1:3]

array([[2, 3],
       [6, 7]])

### 4. fancy 인덱싱
<pre>
fancy 인덱싱은 범위가 아닌 특정 index의 값들을 추출하고 싶을 때 사용
index list 업하여 적용하면 값을 추출할 수 있음
arr[[index list]]
</pre>

In [156]:
# 1차원 fancy 인덱싱

In [162]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])
arr

array([10, 23,  2,  7, 90, 65, 32, 66, 70])

In [165]:
# index를 list로 정의해서 값을 추출
idx = [1, 2, 5]
arr[idx]

array([23,  2, 65])

In [168]:
# 2차원 fancy
# arr2d[[요소1의 행, 요소2의 행], [요소1의 열, 요소2의 열]]

In [170]:
# arr2d[[행index목록],[열index목록]]
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [172]:
arr2d[:, [1, 3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [174]:
arr2d = np.array([ [1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]
                ])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [176]:
arr2d[[1, 2, 0], [1, 2, 1]]

array([ 6, 11,  2])

In [178]:
arr2d[[2],[0,3]]

array([ 9, 12])

## Bool index(Masking)

In [191]:
# np.arange(start, stop, step)
arr = np.arange(10, 61, 10)
arr

array([10, 20, 30, 40, 50, 60])

In [192]:
TFset = [True, False, True]

In [193]:
# does it work?
arr[TFset]
# 1차원 masking 리스트의 개수와 bool 나열 수가 동일하지 않으면 오류

IndexError: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 3

In [194]:
# boolean 값을 list로 작성하여 색인
TFset = [True, False, True, True, False, True]
arr[TFset]

array([10, 30, 40, 60])

In [196]:
# 2차원 boolean index

In [198]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [200]:
# boolean list로 정의, 행단위로 정의
TFset = [True, False]
arr2d[TFset]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2

In [202]:
# boolean list로 정의, 행단위로 정의
TFset = [True, False, False]
arr2d[TFset]

array([[1, 2, 3, 4]])

### 조건 필터
비교 연산자를 활용하여 필터를 생성함
- arr2d[조건필터]

In [205]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [208]:
# ndarray 조건식
# ndarray에 조건식을 주면 boolean 값 반환
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [213]:
3 < arr2d < 8

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [215]:
# arr2d[조건필터]
arr2d[arr2d < 5]

array([1, 2, 3, 4])

In [ ]:
# 문제 shape(3,2,4) ndarray 중 조건 필터 11보다 큰 값 출력
arr3d = [
        ]

In [216]:
arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [222]:
# arr.shape
arr3d = arr.reshape(3,2,4)
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [223]:
arr3d[arr3d > 14]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [237]:
# 2차원 boolindex 부연설명
names = np.array(["aaa", "bbb","ccc", "ddd", "eee", "fff", "ggg"])
data = np.random.rand(7,4)  # random.rand = 0에서 1사이의 값을 랜덤으로 만들어줌
names, data

(array(['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff', 'ggg'], dtype='<U3'),
 array([[0.90558016, 0.65001841, 0.8006867 , 0.93219709],
        [0.22899102, 0.58503953, 0.57530522, 0.87068272],
        [0.19239393, 0.78468962, 0.07773068, 0.46392851],
        [0.89713114, 0.14192497, 0.04306988, 0.50404984],
        [0.40397491, 0.95556538, 0.22455225, 0.59548282],
        [0.44457697, 0.05415633, 0.16501803, 0.27516703],
        [0.47848773, 0.85688266, 0.93178184, 0.04209265]]))

In [238]:
names == "aaa"

array([ True, False, False, False, False, False, False])

In [239]:
# data[names == "aaa"]
data[names == "aaa", :]

array([[0.90558016, 0.65001841, 0.8006867 , 0.93219709]])

In [240]:
names == "ccc"

array([False, False,  True, False, False, False, False])

In [242]:
data[names == "ccc", :]

array([[0.19239393, 0.78468962, 0.07773068, 0.46392851]])

In [245]:
# 문제 : 'ggg'에 대응되는 값 추출
# data[names == "ggg"]
data[names == "ggg", :]

array([[0.47848773, 0.85688266, 0.93178184, 0.04209265]])

In [246]:
# 심화

In [ ]:
names == "