### numpy 객체 연산자 
- (+, -, *)
- ndarray의 shape이 같아야 함

In [6]:
import numpy as np

In [10]:
nums = np.arange(1,7)
nums

array([1, 2, 3, 4, 5, 6])

In [14]:
a = nums.reshape(-1,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b = np.arange(3,9)
b

array([3, 4, 5, 6, 7, 8])

In [27]:
b = b.reshape(-1,3)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [19]:
a + b

array([[ 4,  6,  8],
       [10, 12, 14]])

In [21]:
b = b.reshape(-1,2)
b

array([[3, 4],
       [5, 6],
       [7, 8]])

In [23]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [25]:
print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [38]:
a - b

array([[-2, -2, -2],
       [-2, -2, -2]])

In [40]:
a * b

array([[ 3,  8, 15],
       [24, 35, 48]])

In [42]:
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ]])

In [31]:
# sum - matrix 안에서 sum

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.sum(a, axis=0)

array([5, 7, 9])

In [37]:
np.sum(a, axis=1)

array([ 6, 15])

# 행렬 곱셈 연산은 dot product 사용 !!!
- 내적 : 두 서열의 상응하는 값들의 곱을 더한 것
- shape의 행과 열이 맞는 식의 대응하는 값이 존재해야 계산 가능 / 혹은 행이 1인 경우 (값이 2차원이 아닌 요소로 존재하므로 가능) / 열이 기준이 되어 계산

In [46]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [48]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a.shape, b.shape

((3, 3), (3, 2))

In [52]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [54]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [57]:
# transpose(전치행렬)

In [60]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [65]:
a = np.transpose(b)
a

array([[1, 3, 5],
       [2, 4, 6]])

In [67]:
np.transpose(a)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
# broadcasting
# 숫자의 연산 (단일)


In [83]:
print(a)
print(a.shape)

[[1 3 5]
 [2 4 6]]
(2, 3)


In [75]:
a * 4

array([[ 4, 12, 20],
       [ 8, 16, 24]])

In [84]:
d = np.array([[1, 2, 3]])
print(d)
print(d.shape)

[[1 2 3]]
(1, 3)


In [85]:
a * d

array([[ 1,  6, 15],
       [ 2,  8, 18]])

In [100]:
e = np.array([[1],[2],[3]])
print(e)
print(e.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [101]:
print(d)
print(d.shape)

[[1 2 3]]
(1, 3)


In [103]:
rslt = d * e
print(rslt)
print(rslt.shape)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)


In [106]:
# d와 e2는 계산 안됨 / 차원의 짝이 맞지 않으므로 (e2는 행과 열의 의미가 아닌 요소가 3개라는 뜻)
e2 = np.array([1, 2, 3])
print(e2)
print(e2.shape)

[1 2 3]
(3,)


In [113]:
e + e2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [132]:
# 브로드 캐스팅 실습
Value = np.array([[1,2,3,4],[2,5,6,7],[8,9,10,11],[12,13,14,15]])
print(Value)
Value1 = np.array([1])
print(Value1)
Value2 = np.array([3,3,3,3])
print(Value2)
Value3 = np.array([4,5,6,7]).reshape(4,1)
print(Value3)
Value4 = np.array([[1,2,3,4],[5,6,7,8]])
print(Value4)

[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[1]
[3 3 3 3]
[[4]
 [5]
 [6]
 [7]]
[[1 2 3 4]
 [5 6 7 8]]


In [128]:
# 4x4 + 1
Value + Value1

array([[ 2,  3,  4,  5],
       [ 3,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [127]:
# 4x4 + 1x4
Value + Value2

array([[ 4,  5,  6,  7],
       [ 5,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [126]:
# 1x4 + 4x1
Value2 + Value3

array([[ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10]])

In [129]:
# 4x1 + 1x4
Value3 + Value2

array([[ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10]])

In [140]:
# 차원의 짝이 맞지 않음 (차원 맞춰서 해보기)
print(Value4)
print(Value3)
print(Value4 + Value3)
print(Value3 + Value4)

[[1 2 3 4]
 [5 6 7 8]]
[[4]
 [5]
 [6]
 [7]]


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

### 대각 행렬
- 보통 정방형에서 사용
- N : Row 수 (필수적 요소) 
- M : Column 수(따로 설정하지 않으면 NxN의 정사각 행렬이 만들어짐)
- k : 대각행렬이 값을 가지기 시작하는 위치 
- k의 쓰임 : default는 0, index 0을 기준으로 +는 열 방향 대각, -는 행 방향 대각

In [142]:
# 2 X 2 행렬, 시작위치 0
np.eye(N=2)

array([[1., 0.],
       [0., 1.]])

In [144]:
# 4X4 행렬, 시작 위치 0
np.eye(N=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
# 2X3 행렬, 시작위치 0
np.eye(N=2, M=3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [148]:
# 7X7 행렬, 시작위치 +2
np.eye(7, k=2)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [152]:
# 7X7 행렬, 시작위치 -2
np.eye(7, k=-2)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [153]:
# 7X4 행렬, 시작위치 -2
np.eye(N=7, M=4, k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [161]:
# 3X8 행렬 , 시작위치 -5
np.eye(N=3, M=8, k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [164]:
# 3X8 행렬, 시작위치 +5
np.eye(N=3, M=8, k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [163]:
# 8X3 행렬, 시작위치 -5
np.eye(N=8, M=3, k=-5)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [168]:
# 8X3 행렬, 시작위치 +5
np.eye(N=8, M=3, k=5)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### [문제] 범주형 데이터 숫자로 encoding

In [173]:
import numpy as np

In [176]:
# 1. 범주형 문자열 객체를 만들고 소팅
e_lists=np.array(['주방','폰','욕실','거실'])

In [177]:
np.sort(e_lists)

array(['거실', '욕실', '주방', '폰'], dtype='<U2')

In [179]:
# 2. 문자열을 숫자로 인코딩하는 함수 만들기

In [209]:
# e_lists의 요소를 0~3까지 숫자로 변환하는 함수 
# ['주방','폰','욕실','거실']
# => [2, 3, 1, 0] 로 리턴되도록
def label_encoding(e_lists):
    change_lists=[]
        
    for el in e_lists :
        # 각 문자열을 판단해서 숫자로 대응
        if el == "거실" :
            change_lists.append(0)
        elif el == "욕실" :
            change_lists.append(1)
        elif el == "주방" :
            change_lists.append(2)
        elif el == "폰" :
            change_lists.append(3)
            
    return change_lists

In [208]:
# 범주형 문자열을 정수형 숫자로 바꾸기
np.array(label_encoding(e_lists))

array(None, dtype=object)

In [211]:
# 범주형 문자열을 정수형 숫자로 바꾸기
np.array(label_encoding(e_lists))

array([2, 3, 1, 0])

In [213]:
# one-hot 인코딩 형태로 바꾸기

In [215]:
# [해결방법1] np.eye()를 활용해 적용

In [217]:
values = label_encoding(e_lists)
values

[2, 3, 1, 0]

In [219]:
# 최대값
np.max(values)

3

In [231]:
# 만들 개수 (0부터 시작하므로 최대값에 +1)
n_vals = np.max(values)+1
n_vals

4

In [232]:
# 리스트 넣어서 확인
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [233]:
np.eye(4)[[2,3,1,0]]

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [235]:
np.eye(4)[[2,3,1,0]].astype(int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [242]:
# 변수로 값 적용해보기
# np.eye(n_vals)[values].astype(int)
np.eye(np.size(values))[values].astype(int)

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [243]:
# [해결방법2] np.zeros()로 2차원 배열을 만들고 적용

In [280]:
encoding_nums = np.array(label_encoding(e_lists))
encoding_nums

array([2, 3, 1, 0])

In [281]:
encoding_nums.size

4

In [282]:
# 4 x 4 zero 행렬 생성
one_hot = np.zeros((4,4))
one_hot

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [283]:
# fancy index
# one_hot[[]]
one_hot[[0,1,2,3],[0,1,2,3]] = 1
one_hot

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [284]:
# 4개 요소로 구성된 ndarray 생성
enc_val = np.arange(encoding_nums.size)
enc_val

array([0, 1, 2, 3])

In [293]:
# label -> 숫자로 변형한것
encoding_nums

array([2, 3, 1, 0])

In [294]:
enc_val = np.array(label_encoding(e_lists))
enc_val

array([2, 3, 1, 0])

In [295]:
one_hot = np.zeros((enc_val.size, enc_val.size))
one_hot

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [296]:
one_hot[[np.arange(enc_val.size)], [enc_val]] = 1

In [297]:
one_hot.astype("int8")

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0]], dtype=int8)